name: Deployment auf die Testing EC2 Maschine

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

            - name: checkout
              uses: actions/checkout@v5

            - name: ssh setup
              run: | 
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/ec2-schluessel
                chmod 400 ~/.ssh/ec2-schluessel
                ssh-keyscan -H ${{secrets.EC2_TESTING_IP}}  >> ~/.ssh/known_hosts    

            - name: index.html für nginx bereitstellen
              run: |
                scp -i ~/.ssh/ec2-schluessel 25-08-27-ha/index.html ubuntu@${{secrets.EC2_TESTING_IP}}:/home/ubuntu/index.html
                ssh -i ~/.ssh/ec2-schluessel ubuntu@${{secrets.EC2_TESTING_IP}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html" 
